- id: rye-test
  name: rye-test
  description: Run 'rye test' on your project.
  entry: rye-pre-commit test
  language: python
  types_or: [python, pyi]
  pass_filenames: false
  args: []
- id: rye-lock
  name: rye-lock
  description: Run 'rye lock' when your project requirements change.
  entry: rye-pre-commit lock
  language: python
  pass_filenames: false
  files: ^(.*/)?(requirements(-dev)?\.lock|pyproject\.toml)$
  args: []
- id: rye
  name: rye
  description: Run 'rye' (pass `args` to customize behavior).
  entry: rye-pre-commit
  language: python
  pass_filenames: false
  args: []
- id: rye-with-filenames
  name: rye-with-filenames
  description: Run 'rye' (pass `args` to customize behavior). Filenames of changed files will be provided.
  entry: rye-pre-commit
  language: python
  args: []
